In [72]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [73]:
df = sns.load_dataset('iris')

In [74]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [75]:
df['species'].unique()
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [76]:
from sklearn.model_selection import train_test_split

X = df.drop('species',axis=1)
y = df['species']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [77]:
X_train.head()

     sepal_length  sepal_width  petal_length  petal_width
96            5.7          2.9           4.2          1.3
105           7.6          3.0           6.6          2.1
66            5.6          3.0           4.5          1.5
0             5.1          3.5           1.4          0.2
122           7.7          2.8           6.7          2.0

In [78]:
from sklearn.neighbors import KNeighborsClassifier

model_KNN = KNeighborsClassifier(n_neighbors=3)

In [79]:
model_KNN.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [80]:
model_KNN.score(X_test,y_test)

0.98

In [81]:
#By changing the parameters n_neighbors = [3,5,7,9..] the score changes like 0.98,1.0

In [82]:
from sklearn.svm import SVC

model_svm = SVC(C=30,kernel='linear',gamma='auto')
model_svm.fit(X_train,y_train)

SVC(C=30, gamma='auto', kernel='linear')

In [83]:
model_svm.score(X_test,y_test)

0.98

In [84]:
#By changing the parameters kernel = ['rbf','linear'] and C=1,10,20,30 the score changes like 0.98,1.0

In [85]:
from sklearn.model_selection import GridSearchCV

classifier1 = GridSearchCV((model_svm),{
    'C' : [1,10,20,30,40],
    'kernel' : ['rbf','linear'],
    'gamma' :['auto','scale']
},cv=5,return_train_score=False)

classifier1.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto', kernel='linear'),
             param_grid={'C': [1, 10, 20, 30, 40], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'linear']})

In [86]:
classifier1.cv_results_

{'mean_fit_time': array([0.0025208 , 0.00217848, 0.00223999, 0.00213327, 0.00215454,
        0.002039  , 0.00212078, 0.00209684, 0.00241795, 0.00202398,
        0.00207858, 0.00232964, 0.00211596, 0.00203485, 0.00301194,
        0.00229564, 0.00207663, 0.0022954 , 0.00206838, 0.00207381]),
 'std_fit_time': array([5.37433576e-04, 1.64280014e-04, 8.58527261e-05, 5.59002039e-05,
        8.47373843e-05, 3.27571510e-05, 3.27370154e-05, 3.31490663e-05,
        4.51271280e-04, 1.31760729e-05, 2.92676262e-05, 1.53157943e-04,
        2.64152292e-05, 4.92947695e-05, 1.82888591e-04, 2.12851775e-04,
        2.57492065e-05, 4.03774167e-04, 4.01304861e-05, 4.69127315e-05]),
 'mean_score_time': array([0.00195169, 0.00177298, 0.0016438 , 0.00161943, 0.00161443,
        0.0016047 , 0.00159593, 0.00161467, 0.00165534, 0.00160179,
        0.00158401, 0.00172362, 0.00160217, 0.00162835, 0.00216713,
        0.00161119, 0.00158877, 0.00159597, 0.00158205, 0.00154181]),
 'std_score_time': array([4.54292123e-04, 1.74063629e-04, 4.16501904e-05, 4.11537265e-05,
        5.43992833e-05, 3.07471610e-05, 2.98971194e-05, 5.84987277e-05,
        1.03378032e-04, 8.40257702e-05, 3.46931066e-05, 1.83263949e-04,
        4.65728588e-05, 1.81030861e-04, 8.82471644e-05, 7.15863288e-05,
        3.72309983e-05, 6.09223620e-05, 5.11178775e-05, 2.36062809e-05]),
 'param_C': masked_array(data=[1, 1, 1, 1, 10, 10, 10, 10, 20, 20, 20, 20, 30, 30, 30,
                    30, 40, 40, 40, 40],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'param_gamma': masked_array(data=['auto', 'auto', 'scale', 'scale', 'auto', 'auto',
                    'scale', 'scale', 'auto', 'auto', 'scale', 'scale',
                    'auto', 'auto', 'scale', 'scale', 'auto', 'auto',
                    'scale', 'scale'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 1, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 1, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 20, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 20, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 20, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 20, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 30, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 30, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 30, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 30, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 40, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 40, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 40, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 40, 'gamma': 'scale', 'kernel': 'linear'}],
 'split0_test_score': array([0.95, 1.  , 1.  , 1.  , 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95,
        0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95]),
 'split1_test_score': array([0.9 , 0.9 , 0.85, 0.9 , 0.8 , 0.85, 0.9 , 0.85, 0.8 , 0.85, 0.9 ,
        0.85, 0.8 , 0.85, 0.85, 0.85, 0.8 , 0.85, 0.8 , 0.85]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9,
        0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 0.95, 1.  ,
        0.95, 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ]),
 'split4_test_score': array([0.95, 0.95, 0.9 , 0.95, 1.  , 0.95, 0.95, 0.95, 0.95, 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ]),
 'mean_test_score': array([0.94, 0.95, 0.93, 0.95, 0.93, 0.93, 0.94, 0.93, 0.92, 0.93, 0.95,
        0.93, 0.93, 0.94, 0.94, 0.94, 0.93, 0.94, 0.93, 0.94]),
 'std_test_score': array([0.03741657, 0.04472136, 0.06      , 0.04472136, 0.07483315,
        0.0509902 , 0.03741657, 0.0509902 , 0.0678233 , 0.0509902 ,
        0.04472136, 0.0509902 , 0.07483315, 0.05830952, 0.05830952,
        0.05830952, 0.07483315, 0.05830952, 0.07483315, 0.05830952]),
 'rank_test_score': array([ 4,  1, 11,  1, 11, 16,  4, 16, 20, 16,  1, 16, 11,  6,  6,  6, 11,
         6, 11,  6], dtype=int32)}

In [87]:
result1 = pd.DataFrame(classifier1.cv_results_)
result1

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002521,0.000537,0.001952,0.000454,1,auto,rbf,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}",0.95,0.90,0.9,1.00,0.95,0.94,0.037417,4
1,0.002178,0.000164,0.001773,0.000174,1,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",1.00,0.90,0.9,1.00,0.95,0.95,0.044721,1
2,0.002240,0.000086,0.001644,0.000042,1,scale,rbf,"{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}",1.00,0.85,0.9,1.00,0.90,0.93,0.060000,11
3,0.002133,0.000056,0.001619,0.000041,1,scale,linear,"{'C': 1, 'gamma': 'scale', 'kernel': 'linear'}",1.00,0.90,0.9,1.00,0.95,0.95,0.044721,1
4,0.002155,0.000085,0.001614,0.000054,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,11
5,0.002039,0.000033,0.001605,0.000031,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.95,0.85,0.9,1.00,0.95,0.93,0.050990,16
6,0.002121,0.000033,0.001596,0.000030,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.95,0.90,0.9,1.00,0.95,0.94,0.037417,4
7,0.002097,0.000033,0.001615,0.000058,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.95,0.85,0.9,1.00,0.95,0.93,0.050990,16
8,0.002418,0.000451,0.001655,0.000103,20,auto,rbf,"{'C': 20, 'gamma': 'auto', 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,0.95,0.92,0.067823,20
9,0.002024,0.000013,0.001602,0.000084,20,auto,linear,"{'C': 20, 'gamma': 'auto', 'kernel': 'linear'}",0.95,0.85,0.9,0.95,1.00,0.93,0.050990,16
10,0.002079,0.000029,0.001584,0.000035,20,scale,rbf,"{'C': 20, 'gamma': 'scale', 'kernel': 'rbf'}",0.95,0.90,0.9,1.00,1.00,0.95,0.044721,1
11,0.002330,0.000153,0.001724,0.000183,20,scale,linear,"{'C': 20, 'gamma': 'scale', 'kernel': 'linear'}",0.95,0.85,0.9,0.95,1.00,0.93,0.050990,16
12,0.002116,0.000026,0.001602,0.000047,30,auto,rbf,"{'C': 30, 'gamma': 'auto', 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,11
13,0.002035,0.000049,0.001628,0.000181,30,auto,linear,"{'C': 30, 'gamma': 'auto', 'kernel': 'linear'}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,6
14,0.003012,0.000183,0.002167,0.000088,30,scale,rbf,"{'C': 30, 'gamma': 'scale', 'kernel': 'rbf'}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,6
15,0.002296,0.000213,0.001611,0.000072,30,scale,linear,"{'C': 30, 'gamma': 'scale', 'kernel': 'linear'}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,6
16,0.002077,0.000026,0.001589,0.000037,40,auto,rbf,"{'C': 40, 'gamma': 'auto', 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,11
17,0.002295,0.000404,0.001596,0.000061,40,auto,linear,"{'C': 40, 'gamma': 'auto', 'kernel': 'linear'}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,6
18,0.002068,0.000040,0.001582,0.000051,40,scale,rbf,"{'C': 40, 'gamma': 'scale', 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,11
19,0.002074,0.000047,0.001542,0.000024,40,scale,linear,"{'C': 40, 'gamma': 'scale', 'kernel': 'linear'}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,6

In [88]:
result1[['param_C','param_gamma','param_kernel','mean_test_score']]

    param_C param_gamma param_kernel  mean_test_score
0         1        auto          rbf             0.94
1         1        auto       linear             0.95
2         1       scale          rbf             0.93
3         1       scale       linear             0.95
4        10        auto          rbf             0.93
5        10        auto       linear             0.93
6        10       scale          rbf             0.94
7        10       scale       linear             0.93
8        20        auto          rbf             0.92
9        20        auto       linear             0.93
10       20       scale          rbf             0.95
11       20       scale       linear             0.93
12       30        auto          rbf             0.93
13       30        auto       linear             0.94
14       30       scale          rbf             0.94
15       30       scale       linear             0.94
16       40        auto          rbf             0.93
17       40        auto       linear             0.94
18       40       scale          rbf             0.93
19       40       scale       linear             0.94

In [89]:
from sklearn.model_selection import GridSearchCV

classifier2 = GridSearchCV((model_KNN),{
    'n_neighbors' : [3,5,7,9]
},cv=5,return_train_score=False)

classifier2.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=3),
             param_grid={'n_neighbors': [3, 5, 7, 9]})

In [90]:
classifier2.cv_results_

{'mean_fit_time': array([0.00255446, 0.001934  , 0.00191603, 0.00195394]),
 'std_fit_time': array([7.10888762e-04, 4.30173192e-05, 1.47508479e-05, 9.27024171e-05]),
 'mean_score_time': array([0.00305023, 0.00279078, 0.00280528, 0.00285368]),
 'std_score_time': array([1.13996358e-04, 4.43821420e-05, 6.64125469e-05, 1.36761802e-04]),
 'param_n_neighbors': masked_array(data=[3, 5, 7, 9],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'n_neighbors': 3},
  {'n_neighbors': 5},
  {'n_neighbors': 7},
  {'n_neighbors': 9}],
 'split0_test_score': array([0.95, 0.9 , 0.9 , 0.9 ]),
 'split1_test_score': array([0.85, 0.9 , 0.9 , 0.9 ]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1., 1., 1., 1.]),
 'split4_test_score': array([0.95, 0.95, 0.95, 0.95]),
 'mean_test_score': array([0.93, 0.93, 0.93, 0.93]),
 'std_test_score': array([0.0509902, 0.04     , 0.04     , 0.04     ]),
 'rank_test_score': array([4, 1, 1, 1], dtype=int32)}

In [91]:
result2 = pd.DataFrame(classifier2.cv_results_)
result2

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002554,0.000711,0.003050,0.000114,3,{'n_neighbors': 3},0.95,0.85,0.9,1.0,0.95,0.93,0.05099,4
1,0.001934,0.000043,0.002791,0.000044,5,{'n_neighbors': 5},0.90,0.90,0.9,1.0,0.95,0.93,0.04000,1
2,0.001916,0.000015,0.002805,0.000066,7,{'n_neighbors': 7},0.90,0.90,0.9,1.0,0.95,0.93,0.04000,1
3,0.001954,0.000093,0.002854,0.000137,9,{'n_neighbors': 9},0.90,0.90,0.9,1.0,0.95,0.93,0.04000,1

In [92]:
result2[['param_n_neighbors','mean_test_score']]

   param_n_neighbors  mean_test_score
0                  3             0.93
1                  5             0.93
2                  7             0.93
3                  9             0.93